spring:
    datasource:
        url: jdbc:mysql://localhost:3306/titan_gate?useUnicode=true&characterEncoding=utf8
        hikari:
            driver-class-name: com.mysql.cj.jdbc.Driver
            username: root
            password: 123456
    data:
        redis:
            host: localhost
            port: 6379
    security:
        oauth2:
            client:
                registration:
                    github:
                        client-id: Ov23likcvSZR6zWHPTN4       # ⚠️ 修改为你自己的 GitHub OAuth 应用 ID
                        client-secret: 78830eb5eeda5eb50143030db1140d47bd399c6c  # ⚠️ 修改为你自己的 GitHub OAuth 应用 Secret
                        redirect-uri: http://localhost:${server.port}/login/oauth2/code/github
                        scope:
                            - read:user
                            - user:email
                provider:
                    github:
                        authorization-uri: https://github.com/login/oauth/authorize
                        token-uri: https://github.com/login/oauth/access_token
                        user-info-uri: https://api.github.com/user
                        user-name-attribute: login

dubbo:
    service:
        profile:
            url: tri://localhost:20881

titan:
    gate:
        front-end:
            base-url: http://127.0.0.1:3710
        jwt-secret: q4~@x2uC$f@M2x*^e5&DB^L!3~)6@+
        oauth2:
            callback-url: ${titan.gate.front-end.base-url}/oauth2/callback